Fix docker-compose to use default branch (origin/HEAD) for updates

diff --git a/truenas-docker-compose.yml b/truenas-docker-compose.yml
--- a/truenas-docker-compose.yml
+++ b/truenas-docker-compose.yml
@@ -34,7 +34,7 @@ services:
         else
           echo 'Updating from repository...'
           cd /app/src
-          git fetch origin && git reset --hard origin/main || echo 'Git update failed, using cached version'
+          git fetch origin && git reset --hard origin/HEAD || echo 'Git update failed, using cached version'
         fi
 
         # Generate encryption key if not set
